id/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('card.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('',include('visitor.urls'))
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

visitor/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='visitor'
urlpatterns = [
    
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('list/',views.list_view,name='list'),
    path('checkedin_list/',views.checkedin_list,name='checkedin_list'),
    path('check_out/<pk>/',views.check_out,name='check_out'),
    path('detail/<pk>/',views.detail,name='detail'),
    path('print/<pk>/', views.GeneratePdf.as_view(),name='print'),
]

visitor/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from datetime import datetime

class visitor_detail(models.Model):
    name=models.CharField(max_length=256)
    name_2=models.CharField(max_length=256)
    address=models.CharField(max_length=256)
    id_no=models.CharField(max_length=256)
    id_type=models.CharField(max_length=256)
    mob=models.CharField(max_length=256)
    email=models.CharField(max_length=256)
    veh=models.CharField(max_length=256)
    purpose=models.CharField(max_length=256)
    dest=models.CharField(max_length=256)
    time_in=models.DateTimeField(default=datetime.now, blank=True)
    status_in=models.BooleanField(default=True)
    time_out=models.DateTimeField(default=datetime.now, blank=True)
    #pic = models.ImageField(upload_to = 'images/',null=True,verbose_name="")
    expected_out_time=models.DateTimeField(default=datetime.now, blank=True)
    pic=models.CharField(max_length=100000)

    def __str__(self):
        return self.name

visitor/views.py
from django.shortcuts import render
from visitor.models import visitor_detail
from django.core.mail import EmailMultiAlternatives
from django.utils import timezone
from django.urls import reverse
from datetime import datetime
from django.http import HttpResponse
from django.views.generic import View
from utils import render_to_pdf #created in step 4
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def index(request):
	return render(request,'visitor/index.html')

@login_required
def register(request):
	if request.method=="POST":
		name=request.POST['name']
		name_2=request.POST['name_2']
		address=request.POST['address']
		id_no=request.POST['id_no']
		id_type=request.POST['id_type']
		mob=request.POST['mob']
		email=request.POST['email']
		veh=request.POST['veh']
		purpose=request.POST['purpose']
		dest=request.POST['dest']
		pic=request.POST['pic']
		expected_out_time=request.POST['expected_out_time']
		obj=visitor_detail(name=name,name_2=name_2,address=address,id_no=id_no,id_type=id_type,mob=mob,email=email,veh=veh,purpose=purpose,dest=dest,pic=pic,expected_out_time=expected_out_time)
		obj.save()

		subject, from_email, to = 'Visitor Details at ABV IIITM', 'surjeetsingh41097@gmail.com', email
		text_content = 'This is Visitor ID Card information.'
		html_content = """<h3>Welcome to IIITM, your visiting ID is """+ str(obj.id)+""".</h3>"""+	"""	<table>
		<tr>
			<th colspan="2">Your personal details:</th>
		</tr>
		<tr>
			<td>Name: </td>
			<td>"""+str(obj.name)+"""</td>
		</tr>
		<tr>
			<td>S/D/W/O: </td>
			<td>"""+str(obj.name_2)+"""</td>
		</tr>
		<tr>
			<td>Address: </td>
			<td>"""+str(obj.address)+"""</td>
		</tr>
		<tr>
			<td>ID Type: </td>
			<td>"""+str(obj.id_no)+"""</td>
		</tr>
		<tr>
			<td>Mobile: </td>
			<td>"""+str(obj.mob)+"""</td>
		</tr>
		<tr>
			<td>Email ID: </td>
			<td>"""+str(obj.email)+"""</td>
		</tr>
		<tr>
			<td>Vechile No.: </td>
			<td>"""+str(obj.veh)+"""</td>
		</tr>
		<tr>
			<td>Purpose: </td>
			<td>"""+str(obj.purpose)+"""</td>
		</tr>
		<tr>
			<td>Destination: </td>
			<td>"""+str(obj.dest)+"""</td>
		</tr>
		<tr>
			<td>Check In Time: </td>
			<td>"""+str(obj.time_in)+"""</td>
		</tr>
		<tr>
			<td>Expected Out Time: </td>
			<td>"""+str(obj.expected_out_time)+"""</td>
		</tr>
	</table>"""
		msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
		msg.attach_alternative(html_content, "text/html")
		msg.send()

		#call reminder mail function
		# notify_user(obj.id)

	return render(request,'visitor/new.html')

#code for remind mails functionality
# ----------------------------------------------------------------------------------------------------------
# from background_task import background
# from django.contrib.auth.models import User

# @background(schedule=timezone.now())
# def notify_user(user_id):
# 	user = visitor_detail.objects.get(pk=user_id)
# 	email=user.email
# 	subject, from_email, to = 'Visitor Details at ABV IIITM', 'surjeetsingh41097@gmail.com', email
# 	text_content = 'This is Visitor ID Card information.'
# 	html_content ="Reminder mail.."
# 	msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
# 	msg.attach_alternative(html_content, "text/html")
# 	msg.send() 
	# lookup user by id and send them a message
	# user = visitor_detail.objects.get(pk=user_id)
	# user.email_user('Here is a notification', 'You have been notified')

# -------------------------------------------------------------------------------------------------------------



@login_required
def list_view(request):
	names=''
	id_no=''
	mob_no=''
	time_in=''
	time_out=''
	context={}
	if request.method=='POST':
		names=request.POST['name']
		id_no=request.POST['id_no']
		mob_no=request.POST['mob_no']
		time_in=request.POST['time_in']
		time_out=request.POST['time_out']
		visitors=visitor_detail.objects.filter(status_in=False).\
		filter(name__icontains=names).filter(id_no__icontains=id_no).\
		filter(mob__icontains=mob_no).filter(time_in__gte=time_in).\
		filter(time_out__lte=time_out).order_by('-time_in')
		context={'visitors':visitors}
	else:
		visitors=visitor_detail.objects.filter(status_in=False).order_by('-time_in')
		context={'visitors':visitors}
	return render(request,'visitor/list.html',context=context)

@login_required
def detail(request,pk):
	visitor=visitor_detail.objects.get(id=pk)
	context={'visitor':visitor}
	return render(request,'visitor/detail.html',context=context)

@login_required
def checkedin_list(request):
	names=''
	id_no=''
	mob_no=''
	time_in=''
	time_out=''
	context={}
	if request.method=='POST':
		names=request.POST['name']
		id_no=request.POST['id_no']
		mob_no=request.POST['mob_no']
		time_in=request.POST['time_in']
		time_out=request.POST['time_out']
		visitors=visitor_detail.objects.filter(status_in=True).filter(name__icontains=names).filter(id_no__icontains=id_no).filter(mob__icontains=mob_no).filter(time_in__gte=time_in).filter(time_out__lte=time_out).order_by('-time_in')
		context={'visitors':visitors}
	else:
		visitors=visitor_detail.objects.filter(status_in=True).order_by('-time_in')
		context={'visitors':visitors}
	return render(request,'visitor/checkedin_list.html',context=context)
	
@login_required
def check_out(request,pk):
	visitor=visitor_detail.objects.get(id=pk)
	visitor.time_out=datetime.now()
	visitor.status_in=False
	visitor.save()
	subject, from_email, to = 'Visitor Details at ABV IIITM', 'surjeetsingh41097@gmail.com', visitor.email
	text_content = 'This is Visitor ID Card information.'
	html_content = """<h3>Thanks for Visiting ABV IIITM.</h3>"""+	"""	<table>
	<tr>
		<th colspan="2">Your personal details:</th>
	</tr>
	<tr>
		<td>Name: </td>
		<td>"""+str(visitor.name)+"""</td>
	</tr>
	<tr>
		<td>S/D/W/O: </td>
		<td>"""+str(visitor.name_2)+"""</td>
	</tr>
	<tr>
		<td>Address: </td>
		<td>"""+str(visitor.address)+"""</td>
	</tr>
	<tr>
		<td>ID Type: </td>
		<td>"""+str(visitor.id_no)+"""</td>
	</tr>
	<tr>
		<td>Mobile: </td>
		<td>"""+str(visitor.mob)+"""</td>
	</tr>
	<tr>
		<td>Email ID: </td>
		<td>"""+str(visitor.email)+"""</td>
	</tr>
	<tr>
		<td>Vechile No.: </td>
		<td>"""+str(visitor.veh)+"""</td>
	</tr>
	<tr>
		<td>Purpose: </td>
		<td>"""+str(visitor.purpose)+"""</td>
	</tr>
	<tr>
		<td>Destination: </td>
		<td>"""+str(visitor.dest)+"""</td>
	</tr>
	<tr>
		<td>Check In Time: </td>
		<td>"""+str(visitor.time_in)+"""</td>
	</tr>
	<tr>
		<td>Check Out Time: </td>
		<td>"""+str(visitor.time_out)+"""</td>
	</tr>
</table>"""
	msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
	msg.attach_alternative(html_content, "text/html")
	msg.send()
	context={'visitor':visitor}
	return render(request,'visitor/detail.html',context=context)

class GeneratePdf(View,LoginRequiredMixin):
	def get(self, request, *args, **kwargs):
		primary=self.kwargs['pk']
		visitor=visitor_detail.objects.get(pk=primary)
		data={'visitor':visitor}
		pdf = render_to_pdf('visitor/card.html', data)
		return HttpResponse(pdf, content_type='application/pdf')

templates/visitor/base.html
  

{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="shortcut icon" type="image/png" href="{% static 'card/images/iiitm.png' %}"/>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">



  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">

  <style>
      body { 
        padding-top: 51px; 
      }
          .carousel-inner > .item > img, .carousel-inner > .item > a > img {
        display: block;
        height: 450px;
        min-width: 100%;
        width: 100%;
        max-width: 100%;
        line-height: 1;
    }
      
      .row { margin: 0; padding: 0 }

     .fulll{
    margin-top: 0px;
    height: 100%;
    background-repeat: no-repeat;
    background-image: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));
}

.card-container.card {
    max-width: 350px;
    padding: 40px 40px;
}

.btn {
    font-weight: 700;
    height: 36px;
    -moz-user-select: none;
    -webkit-user-select: none;
    user-select: none;
    cursor: default;
}

/*
 * Card component
 */
.card {
    background-color: #F7F7F7;
    /* just in case there no content*/
    padding: 20px 25px 30px;
    margin: 0 auto 25px;
    margin-top: 50px;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}

.profile-img-card {
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}

/*
 * Form styles
 */
.profile-name-card {
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    margin: 10px 0 0;
    min-height: 1em;
}

.reauth-email {
    display: block;
    color: #404040;
    line-height: 2;
    margin-bottom: 10px;
    font-size: 14px;
    text-align: center;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin #inputEmail,
.form-signin #inputPassword {
    direction: ltr;
    height: 44px;
    font-size: 16px;
}

.form-signin input[type=email],
.form-signin input[type=password],
.form-signin input[type=text],
.form-signin button {
    width: 100%;
    display: block;
    margin-bottom: 10px;
    z-index: 1;
    position: relative;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin .form-control:focus {
    border-color: rgb(104, 145, 162);
    outline: 0;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
}

.btn.btn-signin {
    /*background-color: #4d90fe; */
    background-color: rgb(104, 145, 162);
    /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
    padding: 0px;
    font-weight: 700;
    font-size: 14px;
    height: 36px;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    border: none;
    -o-transition: all 0.218s;
    -moz-transition: all 0.218s;
    -webkit-transition: all 0.218s;
    transition: all 0.218s;
}

.btn.btn-signin:hover,
.btn.btn-signin:active,
.btn.btn-signin:focus {
    background-color: rgb(12, 97, 33);
}

.forgot-password {
    color: rgb(104, 145, 162);
}

.forgot-password:hover,
.forgot-password:active,
.forgot-password:focus{
    color: rgb(12, 97, 33);
}

    </style>
</head>
<body>
    
  <script type="text/javascript">
        $('#myCarousel').carousel();
        var winWidth = $(window).innerWidth();
        $(window).resize(function () {

            if ($(window).innerWidth() < winWidth) {
                $('.carousel-inner>.item>img').css({
                    'min-width': winWidth, 'width': winWidth
                });
            }
            else {
                winWidth = $(window).innerWidth();
                $('.carousel-inner>.item>img').css({
                    'min-width': '', 'width': ''
                });
            }
        });
  </script>

<nav style="margin-top: 0px;" class="navbar navbar-default navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand" href="{%url 'index'%}">Visitor's Identity Portal</a>
    </div>
      
    <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li class="active"><a href="{%url 'index'%}"><i class="fas fa-home"></i>&ensp; Home</a></li>
      <li><a href="{%url 'visitor:register'%}">Add new</a></li>
          <li><a href="{%url 'visitor:checkedin_list'%}">Checked In</a></li>
          <li><a href="{%url 'visitor:list'%}">Checked Out</a></li>
      <!-- <li class="dropdown ">
        <a class="dropdown-toggle " data-toggle="dropdown" href="#">Visitor
        <span class="caret"></span></a>
        <ul class="dropdown-menu ">
          
        </ul>
      </li>   -->      
    </ul>
      
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li><a href="{% url 'logout' %}?next={% url 'index' %}"><i class="fas fa-sign-out-alt"></i>&ensp; Logout</a></li>
      {% else %}
      <li><a href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i>&ensp; Login</a></li>
      {% endif %}
      
    </ul>
  </div>
</div>
</nav>
<div class="row">
        <div class="col-lg-4"><a href=""> <img src="{% static 'card/images/logo-english.png' %}"></a></div>
        <div class="col-lg-4"><a href="{%url 'index'%}"><h2 style="font-family:cursive; color: #192150;">&nbsp Visitor's Identity Portal</h2></a></div>
        <div class="col-lg-4"><a href=""><img src="{% static 'card/images/logo-hindi.png' %}"></a></div>
</div>
<hr/>
 {%block content%}
  {%endblock%}
    
</body>
</html>

templates/visitor/checkedin_list.html
{%extends 'visitor/base.html'%}
{%load static%}

{%block content%}

<form action="{%url 'visitor:checkedin_list'%}" method="POST">
	{%csrf_token%}
	<input type="text" name="name" placeholder="Name">
	<input type="text" name="id_no" placeholder="ID Number">
	<input type="text" name="mob_no" placeholder="Mobile Number">
	<input type="datetime-local" name="time_in" value="2018-06-12 19:30">
	<input type="datetime-local" name="time_out" value="2019-03-12 19:32">
	<input type="submit"  value="submit">
</form>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
  <style>
      body { 
        padding-top: 51px; 
      }
          .carousel-inner > .item > img, .carousel-inner > .item > a > img {
        display: block;
        height: 450px;
        min-width: 100%;
        width: 100%;
        max-width: 100%;
        line-height: 1;
    }
      
  .row { margin: 0; padding: 0 }
      * {
          box-sizing: border-box;
        }
      
  table {
        width:100%;
  }
      
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;

}

th, td {
  padding: 10px;
  text-align: centre;
}
table#mydata tr:nth-child(even) {
  background-color: #eee;
}
table#mydata tr:nth-child(odd) {
 background-color: #fff;
}
table#mydata th {
  opacity: 0.7;
  background-color: black;
  color: white;
}
      
    </style>
</head>
    
    <table class="table-bordered table table-hover" id="mydata">
        <thead>
            <tr>
                <th>Name</th>
        				<th>ID Type</th>
        				<th>ID No.</th>
        				<th>Mob. No.</th>
        				<th>Check In Time</th>
        				<th>Check Out</th>
            </tr>
        </thead>
        <tbody>
        {%for v in visitors%}
					<tr>
						<td><a href="{%url 'visitor:detail' v.id%}">{{v.name}}</a></td>
						<td><a href="{%url 'visitor:detail' v.id%}">{{v.id_type}}</a></td>
						<td><a href="{%url 'visitor:detail' v.id%}">{{v.id_no}}</a></td>
						<td><a href="{%url 'visitor:detail' v.id%}">{{v.mob}}</a></td>
            <td><a href="{%url 'visitor:detail' v.id%}">{{v.time_in}}</a></td>
						<td><a href="{%url 'visitor:detail' v.id%}">Not yet check out</a></td>
					</tr>
				{%endfor%}
            
        </tbody>
    </table>
    <script>
        
        $('#mydata').dataTable();
    </script>
    <br/>
    <br/>
{%endblock%}

templates/visitor/index.html
{%extends 'visitor/base.html'%}
{% load staticfiles %}
{% block active%}
      <li class="active"><a href="{%url 'index'%}"><i class="fas fa-home"></i>&ensp; Home</a></li>
      <li class="dropdown ">
        <a class="dropdown-toggle " data-toggle="dropdown" href="#">Visitor
        <span class="caret"></span></a>
        <ul class="dropdown-menu ">
          <li><a href="{%url 'visitor:register'%}">Add new</a></li>
          <li><a href="{%url 'visitor:checkedin_list'%}">Checked In</a></li>
          <li><a href="{%url 'visitor:list'%}">Checked Out</a></li>
        </ul>
      </li>        
    </ul>
{% endblock active%}
{%block content%}
<head><title>Home</title></head>


  <div id="myCarousel" class="carousel slide" >
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="" contenteditable="false"></li>
        <li data-target="#myCarousel" data-slide-to="1" class="active" contenteditable="false"></li>
        <li data-target="#myCarousel" data-slide-to="2" class="" contenteditable="false"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item" style="">
            <img src="{% static 'card/images/slide1.jpg' %}" alt="" class="img-responsive">
            <!-- <div class="carousel-caption">
                <h4 class="">First Slide Title</h4>
                <p class="">
                   Description for First Slide, this First Slide.
                </p>
            </div> -->
        </div>
        <div class="item active">
            <img src="{% static 'card/images/slide2.jpg' %}" alt="" class="img-responsive">
            <!-- <div class="carousel-caption">
                <h4 class="">Second Slide Title</h4>

                <p class="">
                   Description for Second Slide, this is Second Slide.
                </p>
            </div> -->
        </div>
        <div class="item" style="">
            <img src="{% static 'card/images/slide3.jpg' %}" alt="" class="img-responsive">
            <!-- <div class="carousel-caption">
                <h4 class="">Third Slide Title</h4>

                            <p class="">
                   Description for Third Slide, this is Third Slide.
                </p>
            </div> -->
        </div>
    </div>    

    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>

    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>
<div>
   <h3><u>About Visitor Identity Portal:</u></h3>

<p>Welcome to our website, which allows you to create ID cards for people visiting to your college.</p>
<ul>
	<li>Click <a href="{%url 'visitor:register'%}">here</a> to add new visitor details and create his/her identity card.</li>
    <li>Click <a href="{%url 'visitor:checkedin_list'%}">here</a> to get all visitors currently in the college.</li>
    <li>Click <a href="{%url 'visitor:list'%}">here</a> to check out.</li>
</ul>

<!-- <p>We hope your visit will help you understand the opportunities and potential rewards that are available when you take a proactive approach to your personal financial situation. [Company] created this website to help you gain a better understanding of the financial concepts behind insurance, investing, retirement, estate planning, and wealth preservation. Most importantly, we hope you see the value of working with skilled professionals to pursue your financial goals. We're here to help educate you about the basic concepts of financial planning, to help you learn more about who we are, and to give you fast, easy access to market performance and data. We hope you take advantage of this resource and visit us often. Be sure to add our site to your list of "favorites" in your Internet browser. We frequently update our information, and we wouldn't want you to miss any developments in the area of personal finance.</p> -->

</div>
{%endblock%}